source ~/.zsh_plugins.sh

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=20000
setopt appendhistory sharehistory incappendhistory autocd extendedglob
unsetopt beep nomatch
bindkey -e

## completion style
autoload -U compinit && compinit
bindkey '^[[Z' reverse-menu-complete
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

## History
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
setopt HIST_IGNORE_ALL_DUPS

## Aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias g='git'
alias gco='git checkout'
alias ga='git add'
alias gc='git commit -v'
alias gst='git status'
alias gs='git stash'
alias gl='git log --graph'

if [ -x "kubectl" ]; then
    alias k='kubectl "--context=${KUBECTL_CONTEXT:-$(kubectl config current-context)}" ${KUBECTL_NAMESPACE/[[:alnum:]-]*/--namespace=${KUBECTL_NAMESPACE}}'
fi

if [ -x "go" ]; then
    export PATH=$PATH:/usr/local/go/bin:~/go/bin
fi

if [ -x "direnv" ]; then
    eval "$(direnv hook zsh)"
fi

if [ -x "rbenv" ]; then
    export PATH=$PATH:~/.rbenv/bin:~/.rbenv/plugins/ruby-build/bin

    eval "$(rbenv init -)"
fi

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
